version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - "9999:9999"
  postgres:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    ports:
      - "5432:5432"
